
TOOLPREFIX     ?= i586-mingw32msvc-
CXX		= $(TOOLPREFIX)g++
CC		= $(TOOLPREFIX)gcc
LD		= $(TOOLPREFIX)g++
AR		= $(TOOLPREFIX)ar
RANLIB		= $(TOOLPREFIX)ranlib

CXXFLAGS	+= -I../vamp-plugin-sdk -fno-exceptions -DNDEBUG -O3 -msse -msse2 -Wall -Wextra 
LDFLAGS		:= -L../vamp-plugin-sdk -fno-exceptions -static -shared -lvamp-sdk

PLUGIN_EXT	:= .dll

include Makefile.inc
