
TOOLPREFIX     ?= i586-mingw32msvc-
CXX		= $(TOOLPREFIX)g++
CC		= $(TOOLPREFIX)gcc
LD		= $(TOOLPREFIX)g++
AR		= $(TOOLPREFIX)ar
RANLIB		= $(TOOLPREFIX)ranlib

CXXFLAGS	+= -I../vamp-plugin-sdk -DNDEBUG -O3 -msse -msse2 -Wall -Wextra 
LDFLAGS		:= -L../vamp-plugin-sdk -static -shared -lvamp-sdk -Wl,--retain-symbols-file=vamp-plugin.list

PLUGIN_EXT	:= .dll

include Makefile.inc
